#!/bin/bash
echo "Your mac-address change automatically"
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 5
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 10
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 12
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 15
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 20
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
