#!/bin/bash
echo "Your mac-address change automatically"


macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 5
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 10
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 12
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 15
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 120
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 200
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 300
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 400
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
sleep 500
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
macchanger -a eth0
